inhibit_all_warnings!
use_frameworks!
platform :ios, '8.0'
target 'CheatDictionary' do
    pod 'AFNetworking', '~> 3.0'
    pod 'FMDB'
    pod 'Masonry'
    pod 'UICKeyChainStore'
    pod 'RMStore'
    pod 'HHRouter'
    pod 'ReactiveObjC'
    pod 'BlocksKit'
    pod 'MMDrawerController'
    pod 'WMPageController'
    pod 'SVPullToRefresh'
    pod 'DZNEmptyDataSet'
    pod 'IQKeyboardManager'
    pod 'UIImage-Resize'
    pod 'YYKit'
    pod 'TYAttributedLabel'
    pod 'SDCycleScrollView'
    pod 'MWPhotoBrowser', '~>2.1.2'
    pod 'TZImagePickerController'
    pod 'Toast', '~> 3.1.0'
    pod 'SVProgressHUD'
    pod 'LCActionSheet'
    pod 'LFKit/Component/LFPopupMenu'
    pod 'JYRadarChart'
    pod 'VPImageCropper'
    pod 'TOWebViewController'
    pod 'CNPPopupController'
end
